### ISSUE TITLE
Missing?: "Earth Engine Datalab Initialization.ipynb"

### ISSUE THREAD

**Issue by awhobbs** [tylere/ee-jupyter-examples#1]
This is a very helpful set of notebooks! I'm trying to initialize Earth Engine on a Datalab instance and couldn't find the "`Earth Engine Datalab Initialization`" notebook referenced in the "`Earth Engine and TensorFlow`" notebook. Is it still available, perhaps with a different name?

**Comment by tylere** [comment]
It looks like the notebook referenced was renamed to "1 - Authorize Earth Engine.ipynb". The main purpose of either notebook is to setup authentications credentials on the server running the python kernels for the Jupyter server.

**Comment by awhobbs** [comment]
Oh, yes, that makes sense. Thanks!
