### ISSUE TITLE
import gdal fails

### ISSUE THREAD

**Issue by acocac** [tylere/ee-jupyter-examples#2]
Hi @tylere, I'm wondered how should I set up the gdal library to run the 4 - Earth Engine and TensorFlow nb? Here the error when I import gdal, I'm using MacOS...

```
ImportErrorTraceback (most recent call last)
<ipython-input-1-ecfcf1c998b3> in <module>()
      4 from matplotlib import pyplot
      5 import numpy
----> 6 import gdal
      7 import tempfile
      8 import tensorflow as tf

ImportError: No module named gdal
```

**Comment by tylere** [comment]
If you are using conda, I would suggest trying to install GDAL using conda-forge:
See: https://anaconda.org/conda-forge/gdal

**Comment by acocac** [comment]
@tylere, GDAL (v. 1.10.1-py27_1) is already installed via conda-forge. Please see the attached screenshot... 

![screen shot 2017-11-21 at 21 04 00](https://user-images.githubusercontent.com/13321552/33096622-8f3ca63a-ceff-11e7-8328-e681d3389fe4.png)

**Comment by acocac** [comment]
@tylere I solved it, I was running GCloudDatalab on local machine via docker and it seems libraries were being loaded from /usr/bin/python. My solution was to do the minimal installation using a new env via conda.
